public class Solution {
    public void rotate(int[] nums, int k) {
        k=k%nums.length;
        if(k==0||nums.length<=1)return;
        reverse(nums,0,nums.length-1);
        reverse(nums,0,k-1);
        reverse(nums,k,nums.length-1);
    }
    private void reverse(int [] nums, int i,int j){
        while(i<j){
            int t=nums[i];
            nums[i]=nums[j];
            nums[j]=t;
            i++;j--;
        }
    }
}
